version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.cors.enabled=true
      - http.cors.allow-origin="*"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elastic/elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
        - kong-net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    networks:
        - kong-net

  apm:
    image: docker.elastic.co/apm/apm-server-oss:7.13.0
    container_name: apm
    command: ["sh","-c","chmod go-w /usr/share/apm-server/apm-server.yml && apm-server -e"]
    user: root
    volumes:
    - ./elastic/apm/apm-server.yml:/usr/share/apm-server/apm-server.yml
    ports:
      - "8200:8200"
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge
    external: true